### ISSUE TITLE
crashes with a Null Pointer de-reference on the london hackspace spaceapi

### ISSUE THREAD

**Issue by JasperWallace** [fixme-lausanne/MyHackerspace#30]
Works fine with no widget, but if you do use a widget it crashes, probably due to open being null

https://london.hackspace.org.uk/spaceapi.php

I/MyHackerspace(29223): Update widgetid 39 with url https://london.hackspace.org.uk/spaceapi
V/MyHackerspace(29223): fetching https://london.hackspace.org.uk/spaceapi
D/Launcher.Workspace(12400): 6557954 Animate widget drop, final view is appWidgetHostView
D/AndroidRuntime(29223): Shutting down VM
W/dalvikvm(29223): threadid=1: thread exiting with uncaught exception (group=0x4132e930)
E/AndroidRuntime(29223): FATAL EXCEPTION: main
E/AndroidRuntime(29223): java.lang.NullPointerException
E/AndroidRuntime(29223): 	at ch.fixme.status.Widget$GetApiTask.onPostExecute(Widget.java:232)
E/AndroidRuntime(29223): 	at ch.fixme.status.Widget$GetApiTask.onPostExecute(Widget.java:194)
E/AndroidRuntime(29223): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
E/AndroidRuntime(29223): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(29223): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E/AndroidRuntime(29223): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29223): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(29223): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(29223): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29223): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(29223): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(29223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(29223): 	at dalvik.system.NativeStart.main(Native Method)
W/DropBoxManagerService(  390): Dropping: data_app_crash (966 > 0 bytes)
D/dalvikvm(29223): GC_CONCURRENT freed 565K, 10% free 9441K/10396K, paused 3ms+14ms, total 60ms
D/Launcher.Model(12400): DbDebug    Add item (null) to db, id: 171 (-100, 0, 1, 0)
I/Process (29223): Sending signal. PID: 29223 SIG: 9
I/WindowState(  390): WIN DEATH: Window{42065258 u0 ch.fixme.status/ch.fixme.status.Widget_config}
I/ActivityManager(  390): Process ch.fixme.status (pid 29223) has died.

**Comment by rorist** [comment]
Hello,

Which version do you use ?

Null status is supposed to be fixed in the last version (1.7.4) available on the [play store](https://play.google.com/store/apps/details?id=ch.fixme.status), on [f-droid](https://f-droid.org/repository/browse/?fdid=ch.fixme.status) or from [github](https://github.com/fixme-lausanne/MyHackerspace/blob/master/apks/MyHackerspace-1.7.4.apk).

Cheers

**Comment by JasperWallace** [comment]
I'm using 1.7.4 from f-droid.

More detailed steps to introduce:

install 1.7.4 from f-droid
add the MyHackerSpace widget
select London Hackspace

-> crashes

remove the widget and it's fine.

**Comment by rorist** [comment]
fixed in the 1.8 version
