### ISSUE TITLE
crashes with https://freieslabor.org/api/info

### ISSUE THREAD

**Issue by motp** [fixme-lausanne/MyHackerspace#32]
Space status is shown within the application, but adding a widget for Freies Labor leads to a crash of  MyHackerspace. Widgets for other Hackerspaces are OK.
![myhackerspace_crash](https://cloud.githubusercontent.com/assets/7190467/6473125/819590a4-c1f7-11e4-9387-c03585c37a9d.png)

**Comment by jasontrublu** [comment]
same here :(

**Comment by sedrubal** [comment]
It also crashes, when the cell phone changes the network especially if it changes to a network without internet connection or other broken things (DNS,...)

**Comment by n0skill** [comment]
Thanks for reporting, we're looking into it :)

**Comment by rorist** [comment]
Using the lastest version i guess ? error reporting will be better in the new version, now it can crash the app sometime when there's no error message (could be the case when network is off).. We have to redo a lot of the app though sometime :)

**Comment by sedrubal** [comment]
Yes, the latest version from f-droid.

Thank you ;)

**Comment by jasontrublu** [comment]
I think I found the root cause with freies labor hackerspace. The logo had SSL troubles and could not be loaded. We moved the logo to a different location and both app and widget are stable again

**Comment by motp** [comment]
Yes, I can confirm that :) Thnx!

**Comment by rorist** [comment]
Nice, we've added ssl management using MemorizingTrustManager, maybe it would have helped with the issue..
