### ISSUE TITLE
Quite high battery usage

### ISSUE THREAD

**Issue by sedrubal** [fixme-lausanne/MyHackerspace#33]
On my nexus 5 it needs 24% (android  battery statistic)

**Comment by rorist** [comment]
Hi, are you using the latest version ? because the 1.7.4 version fixes some caching issues (network usage for instance) that might affect battery. 

Do you have only one widget active ? It may have some ghost widget if you didnt reboot for a long time and add/remove the widget multiple times.

**Comment by sedrubal** [comment]
Thank you for your idea.

I have the latest version and I reboot quite often and there is only one widget ;)

Is it possible to rework the spaceapi that the client first downloads a checksum of the json from the server to check, if there are changes?

**Comment by sedrubal** [comment]
Mh it looks like that this issue didn't happened anymore. I'll close this.
