### ISSUE TITLE
Much traffic

### ISSUE THREAD

**Issue by sedrubal** [fixme-lausanne/MyHackerspace#34]
The app needs about 5MB/week. I don't know, if you can fix this or if this is because of the space api design. (Maybe a setting for refresh duration would be nice)

**Comment by diadzine** [comment]
You can set the refresh interval in preferences.

**Comment by sedrubal** [comment]
Oops I'm sorry.

But I had 30 minutes and I think 5mb is quite much anyway...

**Comment by diadzine** [comment]
5mb a week with 30min interval it's 15kb for a spaceapi response. I.e. fixme have 2.5kb.
