### ISSUE TITLE
crashes when network changes

### ISSUE THREAD

**Issue by jasontrublu** [fixme-lausanne/MyHackerspace#41]
Hi,

Often when my smartphone changes networks (wifi -> mobile, wifi -> wifi, between different mobile base stations, etc...) the widget crashes with an notification. This is not a new behaviour, until now I just ignored the problem, but it should be fixable ;-)

Smartphone is a Samsung S5 with Android 5.0 (multiple builds)

**Comment by rorist** [comment]
Hello,

Yes it's annoying, it may have been resolved by a previous commit that was not pushed to the store, I'll have to check and make a new release at some point ! I think I'm going to do a sprint during christmas break (at the Chaos Communication Congress) for a new release, any idea for simple feature would then be nice until then.

Cheers
