### ISSUE TITLE
Show webcam

### ISSUE THREAD

**Issue by dbrgn** [fixme-lausanne/MyHackerspace#45]
Some spaces provide webcam images: http://status.crdmp.ch/

Would be nice if these could be shown. Maybe not automatically, to save bandwidth, but by pressing a button or something like that.

**Comment by rorist** [comment]
Hi, 

indeed, actually it must show the links already, but there's probably a bug. https://github.com/fixme-lausanne/MyHackerspace/blob/master/src/ch/fixme/status/Parse13.java#L201

I'll look into that first, thanks :)

**Comment by dbrgn** [comment]
You're fast :) Cool, thx!
