### ISSUE TITLE
Trust of self-signed certificates

### ISSUE THREAD

**Issue by dbrgn** [fixme-lausanne/MyHackerspace#72]
To continue the discussion in #70: Should we trust self-signed certificates, or certificates where the CA is not in a standard root store (e.g. CaCert)?

Nowadays it should be easy to set up Let's Encrypt, and plain HTTP endpoint URLs still work fine as an alternative. My suggestion would be to keep the certificate validation code.

**Comment by rorist** [comment]
I think it make sense not to trust self signed certifiate silently. We could also send an email to the spaces (the contact should be in the api) which have invalid certs with pointers how to deploy LE.

**Comment by dbrgn** [comment]
> I think it make sense to error in invalid cert and not silently trust them. We could also send an email to the spaces (the contact should be in the api) which have invalid certs with pointers how to deploy LE.

I think @gidsi is already working on a tool that validates things like that :slightly_smiling_face: 

Ok, then I'll close this issue for now.
